#!/bin/sh

set -x
set +e

echo $@
printenv
pwd
ls -l
ls -l dbld/images

OS_PLATFORM=$(basename $DOCKERFILE_PATH .dockerfile)

docker build --build-arg=COMMIT=$(git rev-parse --short HEAD) --build-arg=OS_PLATFORM=${OS_PLATFORM} -t $IMAGE_NAME -f $DOCKERFILE_PATH .
